# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Antti Rautanen
email: antti.v.j.rautanen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Designer/Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anttirautanen.com" # the base hostname & protocol for your site
twitter_username: anttirautanen
github_username:  anttirautanen

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman