name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'

      - uses: actions/checkout@v2

      - name: Install and build
        run: |
          git config --global user.email "tmianttirautanen@gmail.com"
          git config --global user.name "Antti Rautanen (GitHub Action)"
          npm ci
          npm run deploy
